services:
  postgres:
    image: postgres:15
    container_name: backend_postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d backend_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: backend_user_service
    restart: always
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      PORT: ${USER_SERVICE_PORT}
      TCP_PORT: ${TCP_PORT}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
      - "${TCP_PORT}:${TCP_PORT}"

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: backend_auth_service
    restart: always
    env_file:
      - ./.env
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      USER_SERVICE_URL: http://user-service:${USER_SERVICE_PORT}
      POST_SERVICE_URL: http://post-service:${POST_SERVICE_PORT}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRES: ${JWT_ACCESS_EXPIRES}
      JWT_REFRESH_EXPIRES: ${JWT_REFRESH_EXPIRES}
      COOKIE_SECURE: ${COOKIE_SECURE}
      COOKIE_SAMESITE: ${COOKIE_SAMESITE}
      CORS_ORIGIN: ${CORS_ORIGIN}
    command: sh -c "npx prisma migrate deploy && node dist/main"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"

  post-service:
    build:
      context: ./services/post-service
      dockerfile: Dockerfile
    container_name: backend_post_service
    restart: always
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
      AUTH_SERVICE_URL: http://auth-service:${PORT}
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${POST_SERVICE_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${POST_SERVICE_PORT}:${POST_SERVICE_PORT}"

volumes:
  postgres_data:
