services:
  postgres:
    image: postgres:15
    container_name: backend_postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d backend_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: backend_user_service
    restart: always
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      TCP_PORT: ${TCP_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4001:4001"

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: backend_auth_service
    restart: always
    env_file:
      - ./.env
    environment:
      PORT: ${PORT}
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRES: ${JWT_ACCESS_EXPIRES}
      JWT_REFRESH_EXPIRES: ${JWT_REFRESH_EXPIRES}
      COOKIE_SECURE: ${COOKIE_SECURE}
      COOKIE_SAMESITE: ${COOKIE_SAMESITE}
      CORS_ORIGIN: ${CORS_ORIGIN}
    command: sh -c "npx prisma migrate deploy && node dist/main"
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started
    ports:
      - "3000:3000"

volumes:
  postgres_data:
